In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [6]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(4,2)
B = np.random.randn(4,3)
C = np.concatenate((A,B),axis=1)
print(C)

[[-1.05502797  0.19151158  0.45638856  0.01559281  1.45451721]
 [ 0.54563888 -1.1546983  -0.0511545   0.41457682 -1.45170891]
 [-0.70980556 -2.27772704 -0.56973054  1.32227091  0.94142827]
 [-0.88883559  0.04591177 -0.14643696 -0.18900935 -0.17951819]
 [ 1.05950419 -0.85664688  0.59920973 -0.80799492  1.10080617]]
 
[[0.2904805  0.5484873 ]
 [0.91396586 1.14260194]
 [0.46001946 0.31082815]
 [0.15986035 0.52789844]
 [0.84449412 0.05207227]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 0.18630419  0.          0.          0.          0.        ]
 [-1.21291464 -1.56338853  0.          0.          0.        ]
 [ 0.59891034 -0.04629412 -0.72924361  0.          0.        ]
 [ 0.53804071  0.0054788  -1.85412472  0.66474389  0.        ]
 [ 1.28778691  0.68771254  0.04884954 -0.50380976 -0.62491767]]
 
[[ 0.83839298  0.23386177  0.62061766  1.57587924 -2.04719693]
 [ 0.


---
# VIDEO: Matrix addition and subtraction
---


In [8]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[ 0.78540296 -0.06297265 -0.81909563  1.07419566 -1.42909381]
 [-0.23505515 -0.04456817  0.58732649 -0.91646483  0.13193042]
 [-0.70964421  0.08468508 -0.29077613  0.50031823  0.27741708]
 [ 0.61015122  0.95645523  1.04949275  1.09748583  0.73793006]
 [ 1.24387546 -0.4591599  -1.196422   -0.93769389 -0.60548804]]
 
[[ 0.81540296 -0.06297265 -0.81909563  1.07419566 -1.42909381]
 [-0.23505515 -0.01456817  0.58732649 -0.91646483  0.13193042]
 [-0.70964421  0.08468508 -0.26077613  0.50031823  0.27741708]
 [ 0.61015122  0.95645523  1.04949275  1.12748583  0.73793006]
 [ 1.24387546 -0.4591599  -1.196422   -0.93769389 -0.57548804]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [9]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [10]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [11]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [12]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[  7.   1.  -3.   2.]
 [  2.  -1.   0.   5.]
 [ -4.   9.  -4. -10.]
 [  5.  18.   5.  -0.]]
 
[ 7. -1. -4. -0.]
[[ 7.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -4.  0.]
 [ 0.  0.  0. -0.]]
2.0 2.0
